#!/bin/bash
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
WHITE='\033[37m'
BRIGHT_RED='\033[91m'
BRIGHT_GREEN='\033[92m'
BRIGHT_YELLOW='\033[93m'
RESET='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'

architecture=$(hostnamectl | grep -E 'Architecture' | awk -F': ' '{print $2}')
model=$(hostnamectl | grep -E 'Model' | awk -F': ' '{print $2}')
vendor=$(hostnamectl | grep -E 'Vendor' | awk -F': ' '{print $2}')

if [ -f "/etc/os-release" ]; then
    source /etc/os-release
else
    PRETTY_NAME="Unknown"
    VERSION="unknown"
fi

VER="${VERSION:-${BUILD_ID:-unknown}}"

computer="$vendor $model"
user=$(whoami)
hostname=$(hostname)
userfull="$user@$hostname"

width=$(tput cols)

center() {
    local str="$1"
    local str_length=${#str}
    local spaces=$(( (width - str_length) / 2 ))
    printf "%${spaces}s%s\n" "" "$str"
}

available_memory=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
memory=$(free -m | grep -i mem | awk '{print $2}')
available_memory_mb=$((available_memory / 1024))
used_memory=$(( (memory - available_memory_mb) ))

COLOR="${ANSI_COLOR:-$BLUE}"

if command -v figlet &>/dev/null; then
    figlet -f small "$PRETTY_NAME"
else
    echo "$PRETTY_NAME"
fi

center "${COLOR}$userfull${RESET}"
center "=============================   "
center "OS: $PRETTY_NAME $architecture"
center "Version: $VER"
center "Model: $model"
center "Vendor: $vendor"
center "Memory: ${used_memory}/${memory}MB"
